name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: '12'

      - name: Install js dependencies
        run: yarn --frozen-lockfile

      - run: yarn lint --quiet
